### ISSUE TITLE
Handle multiple authors for posts

### ISSUE THREAD

**Issue by prrao87** [kuzudb/blog#3]
- Currently, this template only supports a single author (specified using the `author` field in `src/config/config.json`). 
- What we'd like is to read in the full array of authors from `src/config/authors.json` and reference a subset array of authors in the frontmatter of each post, to allow the post to have one or more authors

There's an existing Astro theme called [Engineering Blog](https://github.com/search?q=repo%3AEddyVinck%2Fastro-engineering-blog%20authors&type=code) that does this, but the code is a little involved for my knowledge of TS. 😅

**Comment by prrao87** [comment]
Hi @mewim the blog content migration is done, and I fixed the aesthetics to the best of my ability. I think it looks pretty good. The only important feature missing right now is the ability to add multiple authors like you did in the docusaurus blog:

Ideally, we'd want the specification to be like before, where we have a list of default authors (us from the Kùzu team), and room to add external authors like this example:

```yaml
authors: 
  - name: Chris Norman
    title: Common Fate
    url: https://www.linkedin.com/in/chrnorm/?originalSubdomain=uk
    image_url: https://www.commonfate.io/_next/image?url=%2Fheadshots%2Fchris.jpg&w=3840&q=75
  - chang
```

I've added the author list to `src/config/authors.json` shown [here](https://github.com/kuzudb/blog/blob/master/src/config/authors.json). But I'm struggling with getting it to actually work because it requires lots of custom JS code. Do you think you could look at this when you have a moment? Thanks!
